base_url = "https://nordic-rse.org/nrse2026"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true

# [markdown]
# highlight_code = false
# highlight_theme = "css"
# smart_punctuation = true

[extra]
footer_text = "This website is built using [Zola](https://www.getzola.org) and the [Academic Workshop](http://github.com/aterenin/academic-workshop/) theme."
title = {tagline = "Presenting the", title = "2026 Nordic-RSE Conference", subtitles = ["June 9-10, Tromsø"]}
banner = {extension = "jpg", size = "cover", fade = true}
buttons = [{name = "About", url = "#about"}, {name = "Venue", url = "#venue"}, {name = "Schedule", url = "https://indico.neic.no/event/290/timetable/#20260609"},{name = "Contact", url = "#contact"},{name = "Code of Conduct", url = "https://nordic-rse.org/events/2026-in-person-conference/code-of-conduct/"}]
image = {resize = 400, ext = '.jpg'}
list_page_limit = 10
header_pages = [{name = "Home", url = "/#home"},{name = "Call for contributions", url = "/#call-for-abstracts"}, {name = "Schedule", url = "/#schedule"},{name = "Venue", url = "/#venue"}]
button_shortcuts = [{variable = "video", name = "Video"}]
